#!/usr/bin/env python3
"""Generates src/tz/tzdata_generated.mbt from a zoneinfo-format directory.

Usage:
    python3 scripts/gen_tzdata.py --source-dir <zoneinfo dir> --output <path>

The source directory is any tree of compiled TZif (RFC 8536) files, such as
a system's /usr/share/zoneinfo or /var/db/timezone/zoneinfo, or one built
from a specific IANA tzdata release with `zic`. Only files that start with
the TZif magic number are treated as zones; everything else (+VERSION,
leapseconds, iso3166.tab, zone.tab, tzdata.zi, the legacy posixrules
compatibility file) is skipped. A symlink is recorded as an alias to its
resolved zone name rather than embedding a duplicate copy of the bytes.
"""

import argparse
import os
import sys

NON_ZONE_NAMES = {"posixrules"}


def is_tzif(path):
    try:
        with open(path, "rb") as f:
            return f.read(4) == b"TZif"
    except OSError:
        return False


def collect(source_dir):
    """Returns (zones: {name: bytes}, aliases: {name: target_name})."""
    zones = {}
    aliases = {}
    for root, _dirs, files in os.walk(source_dir):
        for filename in files:
            path = os.path.join(root, filename)
            name = os.path.relpath(path, source_dir)
            if os.name != "nt":
                name = name.replace(os.sep, "/")
            if os.path.basename(name) in NON_ZONE_NAMES:
                continue
            if os.path.islink(path):
                target = os.path.realpath(path)
                target_name = os.path.relpath(target, source_dir).replace(os.sep, "/")
                aliases[name] = target_name
            elif is_tzif(path):
                with open(path, "rb") as f:
                    zones[name] = f.read()
    # A symlink's target might itself not have been visited as a zone yet
    # (e.g. os.walk order), or might point further through another alias;
    # resolve to a name actually present in `zones`, dropping any alias
    # whose target never resolves to real zone bytes.
    resolved_aliases = {}
    for name, target in aliases.items():
        seen = set()
        while target in aliases and target not in seen:
            seen.add(target)
            target = aliases[target]
        if target in zones:
            resolved_aliases[name] = target
    return zones, resolved_aliases


def mbt_identifier(zone_name, index):
    safe = "".join(c if c.isalnum() else "_" for c in zone_name)
    return "tzdata_zone_%s_%d" % (safe.lower(), index)


def mbt_bytes_literal(data):
    lines = ["(["]
    hexed = ["0x%02X" % b for b in data]
    for i in range(0, len(hexed), 16):
        lines.append("    " + ", ".join(hexed[i : i + 16]) + ",")
    lines.append("  ] : Bytes)")
    return "\n".join(lines)


def mbt_string_literal(s):
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return '"%s"' % escaped


def generate(zones, aliases):
    out = []
    out.append("///|")
    out.append(
        "// Generated by scripts/gen_tzdata.py from a compiled IANA tzdata release."
    )
    out.append("// Do not edit by hand; re-run the script to regenerate.")
    out.append("")
    idents = {}
    for index, name in enumerate(sorted(zones)):
        ident = mbt_identifier(name, index)
        idents[name] = ident
        out.append("///|")
        out.append("let %s : Bytes = %s" % (ident, mbt_bytes_literal(zones[name])))
        out.append("")
    out.append("///|")
    out.append("let tzdata_zones : Map[String, Bytes] = Map::from_array([")
    for name in sorted(zones):
        out.append(
            "  (%s, %s)," % (mbt_string_literal(name), idents[name])
        )
    out.append("])")
    out.append("")
    out.append("///|")
    out.append("let tzdata_aliases : Map[String, String] = Map::from_array([")
    for name in sorted(aliases):
        out.append(
            "  (%s, %s)," % (mbt_string_literal(name), mbt_string_literal(aliases[name]))
        )
    out.append("])")
    out.append("")
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    zones, aliases = collect(args.source_dir)
    if not zones:
        print(f"no TZif zone files found under {args.source_dir}", file=sys.stderr)
        sys.exit(1)
    content = generate(zones, aliases)
    with open(args.output, "w") as f:
        f.write(content)
    print(f"wrote {args.output}: {len(zones)} zones, {len(aliases)} aliases")


if __name__ == "__main__":
    main()
